/**
 * login-form-ft-forms.ts
 *
 * FT form descriptors for LoginForm.
 * Run: npm run generate-ft-forms
 */

import * as path from 'path';
import {writeFt, FtDescriptor} from '@/scripts/generate-ft-forms';

const outDir = path.resolve(
    __dirname, '..', '..', 'app', '(auth)', 'login', '__tests__', 'ft', 'page'
);

const loginFormDescriptor: FtDescriptor = {
    componentName: 'LoginForm',
    reqId: 'FT-14',
    statement: 'LoginForm - renders a login form with email and password fields, runs client-side zod validation before calling the login server action, and redirects the user to their role-specific dashboard on success.',
    props: 'None - the component accepts no props.',
    precondition: [
        'Mock next/navigation: useRouter returns { push: jest.fn() }.',
        'Mock @/lib/controller/auth-controller: login is a jest.fn().',
        'No providers required - the component uses no React context.',
    ].join('\n'),
    renderOutput: [
        'A <form> element.',
        'A <label> "Email" associated with an <input id="email"> of type email.',
        'A <label> "Password" associated with an <input id="password"> of type password.',
        'A <button> with accessible name "Sign in", enabled.',
        'No <Alert> visible (result is null on initial render).',
    ].join('\n'),
    postcondition: [
        'login() called once with a valid LoginUserInput when zod validation passes.',
        'router.push("/admin/dashboard") called when login resolves with role ADMIN.',
        'router.push("/member/dashboard") called when login resolves with role MEMBER.',
        'router.push("/login") called when login resolves with an unrecognised role (switch default).',
        'login() NOT called when zod validation fails - early return fires before startTransition.',
        'Destructive Alert visible with server error message and button re-enabled when login returns success: false.',
    ].join('\n'),
    testingTool: 'Jest + React Testing Library',
    coveragePercent: '100%',
    tcsFailed: 0,
    bugsFound: 0,
    bugsFixed: 'n/a',
    retested: 'not yet',
    retestRun: 0,
    remarks: [
        'Run: npx jest login-form.test.tsx',
        'isPending relies on React 19 async-transition support - startTransition(async fn) keeps isPending=true until the promise resolves.',
        'jsdom does not enforce HTML5 browser validation (type="email", required); the zod safeParse in handleSubmit is the only validation gate tested here.',
        'The switch statement has three branches (ADMIN, MEMBER, default) - each needs its own test case.',
        'Field-level error text is generated by zod and depends on loginUserSchema - tests assert structural presence of error paragraphs, not exact messages.',
    ],
    tcRows: [
        {
            noTc: 'TC-01',
            description: 'Renders email input, password input, and an enabled "Sign in" button with no alert visible in the default idle state.',
            arrange: 'mockLogin not configured (not called).\nrender(<LoginForm />)',
            act: 'No interaction - render only.',
            expectedOutput: [
                'getByLabelText("Email") is in the document.',
                'getByLabelText("Password") is in the document.',
                'getByRole("button", {name: "Sign in"}) is in the document and is enabled.',
                'queryByRole("alert") returns null.',
            ].join('\n'),
            actualResult: 'Passed',
        },
        {
            noTc: 'TC-02',
            description: 'Submitting with both fields empty shows the destructive alert with "Validation failed" and does not call the login server action.',
            arrange: 'mockLogin not configured.\nrender(<LoginForm />)\nNo input typed - both fields remain empty.',
            act: 'userEvent.click(getByRole("button", {name: "Sign in"}))',
            expectedOutput: [
                'getByRole("alert") is in the document and contains text "Validation failed".',
                'mockLogin has not been called.',
            ].join('\n'),
            actualResult: 'Passed',
        },
        {
            noTc: 'TC-03',
            description: 'Submitting with a valid email but an empty password triggers validation failure and does not call the login server action.',
            arrange: 'mockLogin not configured.\nrender(<LoginForm />)\nType "test@example.com" into the Email input; leave Password empty.',
            act: 'userEvent.click(getByRole("button", {name: "Sign in"}))',
            expectedOutput: [
                'getByRole("alert") is in the document (validation failed).',
                'A <p> error element is visible adjacent to the Password input.',
                'No <p> error element is visible adjacent to the Email input.',
                'mockLogin has not been called.',
            ].join('\n'),
            actualResult: 'Passed',
        },
        {
            noTc: 'TC-04',
            description: 'Submitting with an invalid email format and a valid password triggers validation failure and does not call the login server action.',
            arrange: 'mockLogin not configured.\nrender(<LoginForm />)\nType "not-an-email" into the Email input.\nType "Password123!" into the Password input.',
            act: 'userEvent.click(getByRole("button", {name: "Sign in"}))',
            expectedOutput: [
                'getByRole("alert") is in the document (validation failed).',
                'A <p> error element is visible adjacent to the Email input.',
                'No <p> error element is visible adjacent to the Password input.',
                'mockLogin has not been called.',
            ].join('\n'),
            actualResult: 'Passed',
        },
        {
            noTc: 'TC-05',
            description: 'A successful login response with role ADMIN navigates to /admin/dashboard.',
            arrange: 'mockLogin.mockResolvedValueOnce({ success: true, data: { role: Role.ADMIN } }).\nrender(<LoginForm />)\nType valid credentials into both fields.',
            act: 'userEvent.click(getByRole("button", {name: "Sign in"}))',
            expectedOutput: [
                'mockLogin called once with { email: "test@example.com", password: "Password123!" }.',
                'mockPush called once with "/admin/dashboard".',
            ].join('\n'),
            actualResult: 'Passed',
        },
        {
            noTc: 'TC-06',
            description: 'A successful login response with role MEMBER navigates to /member/dashboard.',
            arrange: 'mockLogin.mockResolvedValueOnce({ success: true, data: { role: Role.MEMBER } }).\nrender(<LoginForm />)\nType valid credentials into both fields.',
            act: 'userEvent.click(getByRole("button", {name: "Sign in"}))',
            expectedOutput: [
                'mockLogin called once.',
                'mockPush called once with "/member/dashboard".',
            ].join('\n'),
            actualResult: 'Passed',
        },
        {
            noTc: 'TC-07',
            description: 'A successful login response with an unrecognised role falls through the switch default and navigates to /login.',
            arrange: 'mockLogin.mockResolvedValueOnce({ success: true, data: { role: "UNKNOWN" as Role } }).\nrender(<LoginForm />)\nType valid credentials into both fields.',
            act: 'userEvent.click(getByRole("button", {name: "Sign in"}))',
            expectedOutput: [
                'mockLogin called once.',
                'mockPush called once with "/login".',
            ].join('\n'),
            actualResult: 'Passed',
        },
        {
            noTc: 'TC-08',
            description: 'When the login server action returns success: false the alert shows the server error message and the submit button is re-enabled.',
            arrange: 'mockLogin.mockResolvedValueOnce({ success: false, message: "Invalid credentials" }).\nrender(<LoginForm />)\nType valid credentials into both fields.',
            act: 'userEvent.click(getByRole("button", {name: "Sign in"}))',
            expectedOutput: [
                'getByRole("alert") contains text "Invalid credentials".',
                'getByRole("button", {name: "Sign in"}) is enabled.',
                'mockPush has not been called.',
            ].join('\n'),
            actualResult: 'Passed',
        },
        {
            noTc: 'TC-09',
            description: 'While the login action is in flight the submit button is disabled and its label changes to "Signing in…".',
            arrange: 'mockLogin set to a manually-controlled promise that does not resolve during the assertion.\nrender(<LoginForm />)\nType valid credentials into both fields.',
            act: 'userEvent.click(button) - do not resolve the login promise before asserting.',
            expectedOutput: [
                'getByRole("button") is disabled.',
                'getByText("Signing in…") is in the document.',
                'queryByText("Sign in") is not in the document.',
            ].join('\n'),
            actualResult: 'Passed',
        },
        {
            noTc: 'TC-10',
            description: 'After a server-side failure the user can resubmit and a subsequent valid submission succeeds.',
            arrange: [
                'mockLogin configured with two sequential return values:',
                '  1. { success: false, message: "Invalid credentials" }',
                '  2. { success: true, data: { role: Role.MEMBER } }',
                'render(<LoginForm />)',
                'Type valid credentials into both fields.',
            ].join('\n'),
            act: 'First click - awaited, produces failure.\nSecond click - awaited, produces success.',
            expectedOutput: [
                'After first click: alert with "Invalid credentials" is visible.',
                'After second click: mockPush called with "/member/dashboard".',
                'mockLogin called exactly twice in total.',
            ].join('\n'),
            actualResult: 'Passed',
        },
    ],
};

async function main(): Promise<void> {
    await writeFt(loginFormDescriptor, path.join(outDir, 'login-form-ft-form.xlsx'));
}

main().catch(err => {
    console.error(err);
    process.exit(1);
});